name: Flutter Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. कोड चेकआउट करना
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. जावा एनवायरनमेंट सेट करना
      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. फ़्लटर सेट करना
      - name: Set up Flutter
        uses: actions/subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      # 4. डिपेंडेंसीज इंस्टॉल करना और अंदर वाले प्रोजेक्ट को बिल्ड करना
      - name: Install Dependencies & Build APK
        run: |
          # गिटहब को सीधा आपके प्रोजेक्ट वाले फ़ोल्डर के अंदर भेज रहे हैं
          cd free-pixel-converter
          
          # डिपेंडेंसी गेट करना
          flutter pub get
          
          # एपीके बिल्ड करना
          flutter build apk --release

      # 5. बनी हुई एपीके को डाउनलोड के लिए अपलोड करना
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: free-pixel-converter-apk
          path: "free-pixel-converter/build/app/outputs/flutter-apk/app-release.apk"
